# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/hugo
#image: publysher/hugo:latest
image: zachdeibert/autotools
#image: gohugoio/hugo

pages:
  script:
  - env | sort
  - ./bootstrap
  - mkdir build
  - cd build && ../configure
  - make -C build
  artifacts:
    paths:
    - public/doc/doxygen-doc
  only:
  - master
  
#test:
#  script:
#  - hugo
#  except:
#  - master
