# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/hugo
#image: publysher/hugo:latest
#image: zachdeibert/autotools
image: vdanjean/autotools
#image: gohugoio/hugo

pages:
  script:
  - env | sort
  - for p in autoreconf autoconf automake aclocal; do $p --version | head -1 ; done
  - ./bootstrap
  - mkdir build
  - cd build && ../configure
  - make -C build
  artifacts:
    paths:
    - build/doc/doxygen-doc/html
  only:
  - master
  
#test:
#  script:
#  - hugo
#  except:
#  - master
